### ISSUE TITLE
feature request: enable compatible openai provider

### ISSUE THREAD

**Issue by aborruso** [dsg-polymtl/flockmtl#93]
Hi,
in this way in example, I could use [groq](https://console.groq.com/docs/openai).

Thank you

**Comment by dorbanianas** [comment]
Hey @aborruso
Thanks for the highlight, groq would be a nice provider to have.

Thanks again!

**Comment by aborruso** [comment]
> Thanks for the highlight, groq would be a nice provider to have.

And in general, enable all openai compliant providers.

Thank you

**Comment by aborruso** [comment]
> Thanks for the highlight, groq would be a nice provider to have.

And in general enable all openai compliant providers

**Comment by aborruso** [comment]
And in general enable all openai compliant providers

**Comment by dorbanianas** [comment]
yes that would be good for the 0.3.0 release! Thanks for all your suggestions would be so happy to hear more from you when the release is done.
I will tag you when it's ready ;)

**Comment by aborruso** [comment]
Hi @dorbanianas , I have created a model as in the documentation

```
CREATE SECRET groq (
 TYPE OPENAI,
 BASE_URL 'https://api.groq.com/openai/v1/',
 API_KEY 'xxxxx'
 );
CREATE MODEL(
      'description-model',
      'llama-3.3-70b-versatile',
      'openai',
      {"context_window": 128000, "max_output_tokens": 32000}
  );
```

But if I run `GET MODELS;` I get

```
Catalog Error: Table with name FLOCKMTL_MODEL_DEFAULT_INTERNAL_TABLE does not exist!
Did you mean "flockmtl_config.FLOCKMTL_MODEL_USER_DEFINED_INTERNAL_TABLE"?
```

Is it normal?

Thank you

**Comment by dorbanianas** [comment]
Hey @aborruso, I hope you are doing well! Try to use a memory db or reset your db as the config has been changed

**Comment by dorbanianas** [comment]
Alright let me check

**Comment by dorbanianas** [comment]
I think this is a bug I'm fixing it now and I will create a new PR of it. Thanks for the catch 👌

**Comment by dorbanianas** [comment]
Hey @aborruso, the extension is now available for use! Apologies for the earlier issue, and we hope you enjoy it. We're looking forward to more of your valuable feedback. 😊  

To update, simply run:

```UPDATE EXTENSIONS (flockmtl);```

**Comment by aborruso** [comment]
hi @dorbanianas and thank you.

What am I doing wrong?

![image](https://github.com/user-attachments/assets/7393ee00-adeb-4d4f-8008-3868279e8d16)

**Comment by aborruso** [comment]
Hi @dorbanianas ,
I have set my key in this way. Is it wrong?

```
D CREATE SECRET groq (
     TYPE OPENAI,
     BASE_URL 'https://api.groq.com/openai/v1/',
     API_KEY 'xxxxxxx'
 );

**Comment by dorbanianas** [comment]
so the only missing part is defining the `secret_name` inside the model details. For your case you are naming the secret `groq` so this should be mentioned to be used instead of the default OpenAI API Key.

so your query should be like that:

```
SELECT llm_complete(
        {'model_details': 'description-model', 'secret_name': 'groq'}
        {'prompt': 'Explain the purpose of FlockMTL'}
        ) AS flockmtl_pupose;
        
        ```

**Comment by aborruso** [comment]
Really great, thank you @dorbanianas !!

I need to review the documentation and consider whether to propose adding this obvious but useful note.
