### ISSUE TITLE
How do I save a model and not have to create it every time?

### ISSUE THREAD

**Issue by aborruso** [dsg-polymtl/flockmtl#94]
Hi,
is there a way to make this persistent?

```
CREATE MODEL('gpt-4', 'gpt-4o', 'openai',
    {"context_window": 128000, "max_output_tokens": 4096});
```

Thank you

**Comment by dorbanianas** [comment]
@aborruso you can specify a database name and this would create .db file that would save all your prompts and models.
```
> duckdb my_db.db
```

**Comment by aborruso** [comment]
Then if I use a memory db, I will have to recreate them each time.

And if I today I need to create a new working db, I will have to create them again.

Correct?

**Comment by dorbanianas** [comment]
yeah your right!

**Comment by dorbanianas** [comment]
you can say that the prompt and the models are database information so for each db you need to define your prompts and models

**Comment by aborruso** [comment]
> you can say that the prompt and the models are database information so for each db you need to define your prompts and models

However, as you know, so many models will be useful to me for so many projects. There are some typical operations in each context. It would be useful to have a way to have some of them available permanently. Do I add a feature request?

**Comment by queryproc** [comment]
@aborruso It seems that you find that a set of models and prompts might be used across databases and projects and therefore FlockMTL should have a database of those. Separately, certain models and prompts would be used specifically for a particular database. Is that correct?

For now, we treat them as resources as part of a single database but you bring up an interesting point.

**Comment by queryproc** [comment]
@aborruso let's add it as a feature request and we will think for a way to adopt this!

**Comment by aborruso** [comment]
> @aborruso let's add it as a feature request and we will think for a way to adopt this!

Thank you https://github.com/dsg-polymtl/flockmtl/issues/96
